lists/urls.py
from django.conf.urls import  patterns, url

urlpatterns = patterns('',
        url(r'^(\d+)/$', 'lists.views.view_list', name='view_list'),        
        url(r'^new$', 'lists.views.new_list', name='new_list'),
)

superlists/urls.py
from django.conf.urls import  patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
         url(r'^$', 'lists.views.home_page', name='home'),
         url(r'^lists/', include('lists.urls')),

        #  url(r'^lists/(\d+)/$', 'lists.views.view_list', name='view_list'),
         #
        #  url(r'^lists/new$', 'lists.views.new_list', name='new_list'),
)

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List,default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from lists.models import Item
from django.core.exceptions import ValidationError

DUPLICATE_ITEM_ERROR = "이미 리스트에 해당 아이템이 있습니다."
EMPTY_LIST_ERROR ="You can't have an empty list item."

class ItemForm(forms.models.ModelForm):

    class Meta:
        model  = Item
        fields = ('text',)
        widgets = {
            'text' : forms.fields.TextInput(
            attrs={
                'placeholder':'작업 아이템 입력',
                'class': 'form-control input-lg',

            }),
        }
        error_messages={
        'text':{'required':EMPTY_LIST_ERROR}
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

class ExistingListItemForm(ItemForm):
    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args,**kwargs)
        self.instance.list = for_list

    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text' : [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)

    def save(self):
        return forms.models.ModelForm.save(self)

lists/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from lists.models import Item, List
from django.core.exceptions import ValidationError
from lists.forms import ItemForm, ExistingListItemForm
from lists.models import Item,List

def home_page(request):

    return render(request, 'home.html',{'form':ItemForm()})

def view_list(request,list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)

    if request.method == 'POST':
        form = ExistingListItemForm(for_list=list_,data=request.POST)

        if form.is_valid():
            form.save()
            return redirect(list_)

    return render(request, 'list.html',{'list':list_,"form":form})

def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form":form})

lists/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" media="screen">
    <link rel="stylesheet" href="/static/base.css" media="screen">


    <title>To-Do lists</title>
  </head>

  <body>

  <div class="row">
    <div class="col-md-6 col-md-offset-3 jumbotron">
      <div class="text-center">
        <h1>{% block header_text%} {% endblock %}</h1>
          <form method="POST" action="{% block form_action%} {% endblock%}">
              {{form.text}}
              {% csrf_token %}
              {% if form.errors %}
                <div class="form-group has-error">
                  <span class="help-block">
                    {{form.text.errors}}
                  </span>
                </div>
              {% endif  %}
          </form>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      {% block table%}

      {% endblock %}
    </div>
  </div>



  <script src="http://code.jquery.com/jquery.min.js"></script>
  <script src="/static/list.js"></script>
  </body>
</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}작업목록 시작{% endblock%}
{% block form_action%}{% url 'new_list' %}{%endblock%}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock%}
{% block form_action%}{% url 'view_list' list.id %}{%endblock%}
{% block table %}
  <table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
    <tr>
      <td>{{forloop.counter}}: {{item.text}}</td>
      {% endfor %}
    </tr>
  </table>
{% endblock%}